name: AWS Device Farm CI

on:
  push:
    branches:
      [ "master", main, draft ]
  pull_request:
    branches: [ "master", main, draft ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: echo "Android SDK is set up"

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: echo "Android Emulator is started"

      - name: Build and run tests
        run: ./gradlew build connectedAndroidTest

      - name: Zip test results
        if: always()
        run: |
          if [ -d "./app/build/outputs/androidTest-results/connected" ]; then
            zip -r test-results.zip ./app/build/outputs/androidTest-results/connected
          else
            echo "No test results found."
            touch test-results.zip
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.zip
